-- Мини-дамп каталога для локальной разработки: фильмы, сериалы, книги, игры, люди, теги.
-- Загрузка: make seed (вместе с dev.sql), после старта приложения: нужны применённые миграции.
-- Повторный запуск безопасен: существующие записи (по slug) не трогаются.
--
-- Подобраны франшизы, где одно произведение есть в нескольких типах (книга → фильм → игра):
-- на них видна главная идея Nexus — обсуждения и подборки сразу по нескольким сущностям.
--
-- metadata должна соответствовать схемам из modules/catalog/src/metadata.rs: это проверяет
-- тест seed_catalog_is_valid (app/tests/catalog.rs). Связи пишутся через подзапросы по slug:
-- опечатка в slug даёт NOT NULL violation, а не тихо потерянную строку.
--
-- Meilisearch не видит данные, загруженные в обход API: make seed после загрузки
-- перестраивает индекс (POST /api/v1/catalog/admin/search/reindex).

BEGIN;

INSERT INTO tags (slug, name) VALUES
    ('sci-fi',          'Научная фантастика'),
    ('fantasy',         'Фэнтези'),
    ('horror',          'Ужасы'),
    ('drama',           'Драма'),
    ('thriller',        'Триллер'),
    ('space-opera',     'Космическая опера'),
    ('cyberpunk',       'Киберпанк'),
    ('post-apocalypse', 'Постапокалипсис'),
    ('dystopia',        'Антиутопия'),
    ('adventure',       'Приключения'),
    ('detective',       'Детектив'),
    ('based-on-book',   'Экранизация'),
    ('rpg',             'Ролевая игра'),
    ('open-world',      'Открытый мир'),
    ('shooter',         'Шутер'),
    ('classic',         'Классика'),
    ('animation',       'Анимация'),
    ('philosophy',      'Философское')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO entities (kind, slug, title, original_title, release_date, description, metadata) VALUES
    -- Дюна
    ('book',   'dune-novel', 'Дюна', 'Dune', '1965-08-01',
     'Пол Атрейдес и пустынная планета Арракис — единственный источник пряности во Вселенной.',
     '{"isbn": "9780441013593", "pages": 896, "publisher": "Ace Books"}'),
    ('book',   'dune-messiah', 'Мессия Дюны', 'Dune Messiah', '1969-10-15',
     'Двенадцать лет спустя: Пол — император, а его джихад охватил Вселенную.',
     '{"pages": 256, "publisher": "G. P. Putnam''s Sons"}'),
    ('movie',  'dune-1984', 'Дюна', 'Dune', '1984-12-14',
     'Первая экранизация романа Херберта, снятая Дэвидом Линчем.',
     '{"runtime_min": 137, "countries": ["US"], "age_rating": "PG-13"}'),
    ('movie',  'dune-2021', 'Дюна', 'Dune', '2021-10-22',
     'Первая часть экранизации Дени Вильнёва: семья Атрейдес принимает Арракис.',
     '{"runtime_min": 155, "countries": ["US", "CA"], "age_rating": "PG-13"}'),
    ('movie',  'dune-part-two-2024', 'Дюна: Часть вторая', 'Dune: Part Two', '2024-03-01',
     'Пол объединяется с фрименами и Чани, чтобы отомстить Харконненам.',
     '{"runtime_min": 166, "countries": ["US", "CA"], "age_rating": "PG-13"}'),

    -- Ведьмак
    ('book',   'the-last-wish', 'Последнее желание', 'Ostatnie życzenie', '1993-01-01',
     'Сборник рассказов о ведьмаке Геральте из Ривии.',
     '{"isbn": "9780316029186", "pages": 384, "publisher": "SuperNowa"}'),
    ('series', 'the-witcher-series', 'Ведьмак', 'The Witcher', '2019-12-20',
     'Сериал Netflix по книгам Анджея Сапковского.',
     '{"seasons": 4, "episodes": 32, "status": "ongoing", "countries": ["US", "PL"]}'),
    ('game',   'the-witcher-3-wild-hunt', 'Ведьмак 3: Дикая Охота', 'The Witcher 3: Wild Hunt', '2015-05-19',
     'Геральт ищет Цири, которую преследует Дикая Охота.',
     '{"platforms": ["pc", "ps4", "xbox-one", "switch", "ps5", "xbox-series"], "developer": "CD Projekt Red", "publisher": "CD Projekt"}'),

    -- Средиземье
    ('book',   'the-hobbit-novel', 'Хоббит, или Туда и обратно', 'The Hobbit', '1937-09-21',
     'Бильбо Бэггинс отправляется с гномами к Одинокой горе.',
     '{"isbn": "9780547928227", "pages": 300, "publisher": "George Allen & Unwin"}'),
    ('book',   'the-lord-of-the-rings-novel', 'Властелин колец', 'The Lord of the Rings', '1954-07-29',
     'Фродо должен уничтожить Кольцо Всевластья в огне Роковой горы.',
     '{"isbn": "9780544003415", "pages": 1178, "publisher": "George Allen & Unwin"}'),
    ('movie',  'lotr-fellowship-2001', 'Властелин колец: Братство Кольца', 'The Lord of the Rings: The Fellowship of the Ring', '2001-12-19',
     'Девять путников отправляются в Мордор.',
     '{"runtime_min": 178, "countries": ["NZ", "US"], "age_rating": "PG-13"}'),
    ('movie',  'lotr-two-towers-2002', 'Властелин колец: Две крепости', 'The Lord of the Rings: The Two Towers', '2002-12-18',
     'Братство распалось, а Рохан готовится к битве у Хельмовой Пади.',
     '{"runtime_min": 179, "countries": ["NZ", "US"], "age_rating": "PG-13"}'),
    ('movie',  'lotr-return-of-the-king-2003', 'Властелин колец: Возвращение короля', 'The Lord of the Rings: The Return of the King', '2003-12-17',
     'Последняя битва за Средиземье.',
     '{"runtime_min": 201, "countries": ["NZ", "US"], "age_rating": "PG-13"}'),
    ('movie',  'the-hobbit-unexpected-journey-2012', 'Хоббит: Нежданное путешествие', 'The Hobbit: An Unexpected Journey', '2012-12-14',
     'Первая часть трилогии по «Хоббиту».',
     '{"runtime_min": 169, "countries": ["NZ", "US"], "age_rating": "PG-13"}'),

    -- Стивен Кинг
    ('book',   'the-shining-novel', 'Сияние', 'The Shining', '1977-01-28',
     'Писатель Джек Торранс с семьёй зимует в пустом отеле «Оверлук».',
     '{"isbn": "9780307743657", "pages": 447, "publisher": "Doubleday"}'),
    ('movie',  'the-shining-1980', 'Сияние', 'The Shining', '1980-05-23',
     'Экранизация Стэнли Кубрика, которую Кинг не любит.',
     '{"runtime_min": 146, "countries": ["GB", "US"], "age_rating": "R"}'),
    ('book',   'it-novel', 'Оно', 'It', '1986-09-15',
     'Семеро друзей из Дерри против древнего зла.',
     '{"isbn": "9781501142970", "pages": 1138, "publisher": "Viking"}'),
    ('movie',  'it-2017', 'Оно', 'It', '2017-09-08',
     'Клуб неудачников и клоун Пеннивайз.',
     '{"runtime_min": 135, "countries": ["US", "CA"], "age_rating": "R"}'),

    -- Киберпанк
    ('book',   'neuromancer', 'Нейромант', 'Neuromancer', '1984-07-01',
     'Хакер Кейс получает последний шанс вернуться в киберпространство.',
     '{"isbn": "9780441569595", "pages": 271, "publisher": "Ace Books"}'),
    ('book',   'do-androids-dream', 'Мечтают ли андроиды об электроовцах?', 'Do Androids Dream of Electric Sheep?', '1968-01-01',
     'Охотник за головами Рик Декард выслеживает беглых андроидов.',
     '{"isbn": "9780345404473", "pages": 210, "publisher": "Doubleday"}'),
    ('movie',  'blade-runner-1982', 'Бегущий по лезвию', 'Blade Runner', '1982-06-25',
     'Вольная экранизация романа Филипа Дика.',
     '{"runtime_min": 117, "countries": ["US"], "age_rating": "R"}'),
    ('movie',  'blade-runner-2049', 'Бегущий по лезвию 2049', 'Blade Runner 2049', '2017-10-06',
     'Тридцать лет спустя офицер К находит тайну, способную разрушить общество.',
     '{"runtime_min": 164, "countries": ["US", "GB", "CA"], "age_rating": "R"}'),
    ('game',   'cyberpunk-2077', 'Cyberpunk 2077', NULL, '2020-12-10',
     'Наёмник Ви и цифровой призрак Джонни Сильверхенда в Найт-Сити.',
     '{"platforms": ["pc", "ps4", "xbox-one", "ps5", "xbox-series"], "developer": "CD Projekt Red", "publisher": "CD Projekt"}'),
    ('series', 'cyberpunk-edgerunners', 'Киберпанк: Бегущие по краю', 'Cyberpunk: Edgerunners', '2022-09-13',
     'Аниме во вселенной Cyberpunk 2077.',
     '{"seasons": 1, "episodes": 10, "status": "ended", "countries": ["JP", "PL"]}'),

    -- Стругацкие, Лем, Оруэлл
    ('book',   'roadside-picnic', 'Пикник на обочине', NULL, '1972-01-01',
     'Сталкер Рэдрик Шухарт ходит в Зону за артефактами пришельцев.',
     '{"isbn": "9781613743416", "pages": 224, "publisher": "Молодая гвардия"}'),
    ('movie',  'stalker-1979', 'Сталкер', NULL, '1979-05-25',
     'Тарковский по сценарию Стругацких: путь к Комнате, исполняющей желания.',
     '{"runtime_min": 163, "countries": ["SU"]}'),
    ('game',   'stalker-shadow-of-chernobyl', 'S.T.A.L.K.E.R.: Тень Чернобыля', 'S.T.A.L.K.E.R.: Shadow of Chernobyl', '2007-03-20',
     'Меченый идёт к центру Зоны отчуждения.',
     '{"platforms": ["pc"], "developer": "GSC Game World", "publisher": "THQ"}'),
    ('game',   'stalker-2', 'S.T.A.L.K.E.R. 2: Сердце Чернобыля', 'S.T.A.L.K.E.R. 2: Heart of Chornobyl', '2024-11-20',
     'Возвращение в Зону спустя семнадцать лет.',
     '{"platforms": ["pc", "xbox-series"], "developer": "GSC Game World", "publisher": "GSC Game World"}'),
    ('book',   'solaris-novel', 'Солярис', 'Solaris', '1961-01-01',
     'Океан планеты Солярис материализует воспоминания людей.',
     '{"pages": 204, "publisher": "Wydawnictwo Ministerstwa Obrony Narodowej"}'),
    ('movie',  'solaris-1972', 'Солярис', NULL, '1972-03-20',
     'Экранизация Тарковского.',
     '{"runtime_min": 167, "countries": ["SU"]}'),
    ('book',   'nineteen-eighty-four', '1984', 'Nineteen Eighty-Four', '1949-06-08',
     'Старший Брат следит за тобой.',
     '{"isbn": "9780451524935", "pages": 328, "publisher": "Secker & Warburg"}'),

    -- Песнь льда и пламени
    ('book',   'a-game-of-thrones', 'Игра престолов', 'A Game of Thrones', '1996-08-01',
     'Первая книга цикла «Песнь льда и пламени».',
     '{"isbn": "9780553593716", "pages": 694, "publisher": "Bantam Spectra"}'),
    ('series', 'game-of-thrones-series', 'Игра престолов', 'Game of Thrones', '2011-04-17',
     'Борьба за Железный трон по книгам Джорджа Мартина.',
     '{"seasons": 8, "episodes": 73, "status": "ended", "countries": ["US", "GB"]}'),
    ('series', 'house-of-the-dragon', 'Дом Дракона', 'House of the Dragon', '2022-08-21',
     'Танец драконов: гражданская война Таргариенов за двести лет до «Игры престолов».',
     '{"seasons": 2, "episodes": 18, "status": "ongoing", "countries": ["US"]}'),

    -- Метро
    ('book',   'metro-2033-novel', 'Метро 2033', NULL, '2005-01-01',
     'После ядерной войны люди живут на станциях московского метро.',
     '{"pages": 384, "publisher": "Эксмо"}'),
    ('game',   'metro-2033-game', 'Метро 2033', 'Metro 2033', '2010-03-16',
     'Артём идёт через метро, чтобы спасти ВДНХ.',
     '{"platforms": ["pc", "xbox-360"], "developer": "4A Games", "publisher": "THQ"}'),
    ('game',   'metro-exodus', 'Метро: Исход', 'Metro Exodus', '2019-02-15',
     'Артём и «Спарта» покидают Москву на поезде «Аврора».',
     '{"platforms": ["pc", "ps4", "xbox-one"], "developer": "4A Games", "publisher": "Deep Silver"}'),

    -- Космос
    ('movie',  'interstellar', 'Интерстеллар', 'Interstellar', '2014-11-07',
     'Экспедиция через червоточину в поисках нового дома для человечества.',
     '{"runtime_min": 169, "countries": ["US", "GB"], "age_rating": "PG-13"}'),
    ('movie',  'arrival-2016', 'Прибытие', 'Arrival', '2016-11-11',
     'Лингвист учится говорить с пришельцами и иначе видеть время.',
     '{"runtime_min": 116, "countries": ["US"], "age_rating": "PG-13"}'),
    ('book',   'leviathan-wakes', 'Пробуждение Левиафана', 'Leviathan Wakes', '2011-06-15',
     'Первая книга цикла «Пространство».',
     '{"pages": 592, "publisher": "Orbit"}'),
    ('series', 'the-expanse', 'Пространство', 'The Expanse', '2015-12-14',
     'Земля, Марс и Пояс на грани войны.',
     '{"seasons": 6, "episodes": 62, "status": "ended", "countries": ["US"]}'),
    ('game',   'mass-effect', 'Mass Effect', NULL, '2007-11-20',
     'Капитан Шепард и «Нормандия» против Жнецов.',
     '{"platforms": ["xbox-360", "pc", "ps3"], "developer": "BioWare", "publisher": "Microsoft Game Studios"}'),

    -- Другое
    ('game',   'the-last-of-us', 'Одни из нас', 'The Last of Us', '2013-06-14',
     'Джоэл и Элли пересекают Америку после пандемии кордицепса.',
     '{"platforms": ["ps3"], "developer": "Naughty Dog", "publisher": "Sony Computer Entertainment"}'),
    ('series', 'the-last-of-us-series', 'Одни из нас', 'The Last of Us', '2023-01-15',
     'Сериал HBO по игре Naughty Dog.',
     '{"seasons": 2, "episodes": 16, "status": "ongoing", "countries": ["US"]}'),
    ('series', 'stranger-things', 'Очень странные дела', 'Stranger Things', '2016-07-15',
     'Хоукинс, Изнанка и девочка с суперспособностями.',
     '{"seasons": 5, "episodes": 42, "status": "ended", "countries": ["US"]}'),
    ('game',   'elden-ring', 'Elden Ring', NULL, '2022-02-25',
     'Междуземье, Погасшие и осколки Кольца Элден. Мир придуман вместе с Джорджем Мартином.',
     '{"platforms": ["pc", "ps4", "ps5", "xbox-one", "xbox-series"], "developer": "FromSoftware", "publisher": "Bandai Namco Entertainment"}')
ON CONFLICT (slug) DO NOTHING;

-- Постеры, обложки и трейлеры. Отдельным UPDATE, а не в INSERT выше: ON CONFLICT DO NOTHING
-- не трогает уже загруженные строки, а так повторный make seed дополняет и старую базу.
-- Картинки — ссылки на CDN (TMDB, Open Library, Steam), файлы не храним.
-- Трейлеры — источники по приоритету: YouTube с канала правообладателя, затем Rutube для стран,
-- где YouTube заблокирован (официальных каналов там нет — это загрузки сторонних каналов,
-- для прода заменить официальными). Фронтенд показывает первый доступный зрителю источник;
-- нет ни одного — только постер. `- 'trailer'` убирает поле прежнего формата.
UPDATE entities e
SET cover_url = v.cover_url,
    metadata = CASE WHEN v.trailers IS NULL THEN e.metadata - 'trailer'
                    ELSE (e.metadata - 'trailer') || jsonb_build_object('trailers', v.trailers::jsonb) END
FROM (VALUES
    ('dune-1984',
     'https://image.tmdb.org/t/p/w780/8F6LqsbPRaZIUFDt7V1Rpyh3O8L.jpg',
     NULL),
    ('dune-2021',
     'https://image.tmdb.org/t/p/w780/x2Jloj3InKrmTyHJKFviBAdZG0S.jpg',
     '[{"provider": "youtube", "id": "n9xhJrPXop4"}, {"provider": "rutube", "id": "0ab1fc1e47f2e9b89e9e59d9db36f2b4"}]'),
    ('dune-part-two-2024',
     'https://image.tmdb.org/t/p/w780/pB3Hox16z3LqiBLmXZsxV9dE6EJ.jpg',
     '[{"provider": "youtube", "id": "Way9Dexny3w"}, {"provider": "rutube", "id": "264355f929e2781efa3153905b5d5ea3"}]'),
    ('lotr-fellowship-2001',
     'https://image.tmdb.org/t/p/w780/plCqhwzN9xw09ImTnnInwSEwJBA.jpg',
     '[{"provider": "youtube", "id": "V75dMMIW2B4"}, {"provider": "rutube", "id": "a46f055880d7fd9de4db6a8872831deb"}]'),
    ('lotr-two-towers-2002',
     'https://image.tmdb.org/t/p/w780/tGoC0XMAHrDm8iZlDWI4uk80kdo.jpg',
     NULL),
    ('the-witcher-series',
     'https://image.tmdb.org/t/p/w780/rY2c2LhN07CRKlAbRaDZxN2XjvK.jpg',
     '[{"provider": "youtube", "id": "cSqi-8kAMmM"}, {"provider": "rutube", "id": "b75dbc75330a8ffb5b2efc47c052b306"}]'),
    ('the-witcher-3-wild-hunt',
     'https://steamcdn-a.akamaihd.net/steam/apps/292030/library_600x900_2x.jpg',
     '[{"provider": "youtube", "id": "1-l29HlKkXU"}, {"provider": "rutube", "id": "79f9adf82e1df26f6a7053ad49e8b9b1"}]'),
    ('dune-novel',
     'https://covers.openlibrary.org/b/isbn/9780441013593-L.jpg',
     NULL),
    ('the-last-wish',
     'https://covers.openlibrary.org/b/isbn/9780316029186-L.jpg',
     NULL),
    ('the-hobbit-novel',
     'https://covers.openlibrary.org/b/isbn/9780618260300-L.jpg',
     NULL),
    ('the-lord-of-the-rings-novel',
     'https://covers.openlibrary.org/b/isbn/9780544003415-L.jpg',
     NULL)
) AS v (slug, cover_url, trailers)
WHERE e.slug = v.slug;

INSERT INTO people (slug, full_name, birth_date, bio) VALUES
    ('frank-herbert',       'Фрэнк Херберт',        '1920-10-08', 'Американский писатель-фантаст, автор «Дюны».'),
    ('denis-villeneuve',    'Дени Вильнёв',         '1967-10-03', 'Канадский режиссёр.'),
    ('david-lynch',         'Дэвид Линч',           '1946-01-20', 'Американский режиссёр.'),
    ('timothee-chalamet',   'Тимоти Шаламе',        '1995-12-27', NULL),
    ('zendaya',             'Зендея',               '1996-09-01', NULL),
    ('kyle-maclachlan',     'Кайл Маклахлен',       '1959-02-22', NULL),
    ('hans-zimmer',         'Ханс Циммер',          '1957-09-12', 'Композитор.'),
    ('andrzej-sapkowski',   'Анджей Сапковский',    '1948-06-21', 'Польский писатель, автор «Ведьмака».'),
    ('henry-cavill',        'Генри Кавилл',         '1983-05-05', NULL),
    ('jrr-tolkien',         'Джон Р. Р. Толкин',    '1892-01-03', 'Английский писатель и филолог.'),
    ('peter-jackson',       'Питер Джексон',        '1961-10-31', 'Новозеландский режиссёр.'),
    ('elijah-wood',         'Элайджа Вуд',          '1981-01-28', NULL),
    ('ian-mckellen',        'Иэн Маккеллен',        '1939-05-25', NULL),
    ('stephen-king',        'Стивен Кинг',          '1947-09-21', 'Американский писатель, «король ужасов».'),
    ('stanley-kubrick',     'Стэнли Кубрик',        '1928-07-26', 'Американский режиссёр.'),
    ('jack-nicholson',      'Джек Николсон',        '1937-04-22', NULL),
    ('andy-muschietti',     'Андрес Мускетти',      '1973-08-26', 'Аргентинский режиссёр.'),
    ('william-gibson',      'Уильям Гибсон',        '1948-03-17', 'Писатель, один из основателей киберпанка.'),
    ('philip-k-dick',       'Филип К. Дик',         '1928-12-16', 'Американский писатель-фантаст.'),
    ('ridley-scott',        'Ридли Скотт',          '1937-11-30', 'Британский режиссёр.'),
    ('harrison-ford',       'Харрисон Форд',        '1942-07-13', NULL),
    ('ryan-gosling',        'Райан Гослинг',        '1980-11-12', NULL),
    ('keanu-reeves',        'Киану Ривз',           '1964-09-02', NULL),
    ('arkady-strugatsky',   'Аркадий Стругацкий',   '1925-08-28', 'Советский писатель-фантаст.'),
    ('boris-strugatsky',    'Борис Стругацкий',     '1933-04-15', 'Советский писатель-фантаст.'),
    ('andrei-tarkovsky',    'Андрей Тарковский',    '1932-04-04', 'Советский режиссёр.'),
    ('stanislaw-lem',       'Станислав Лем',        '1921-09-12', 'Польский писатель-фантаст и философ.'),
    ('george-orwell',       'Джордж Оруэлл',        '1903-06-25', 'Британский писатель.'),
    ('george-rr-martin',    'Джордж Р. Р. Мартин',  '1948-09-20', 'Американский писатель, автор «Песни льда и пламени».'),
    ('dmitry-glukhovsky',   'Дмитрий Глуховский',   '1979-06-12', 'Писатель, автор «Метро 2033».'),
    ('christopher-nolan',   'Кристофер Нолан',      '1970-07-30', 'Британо-американский режиссёр.'),
    ('matthew-mcconaughey', 'Мэттью Макконахи',     '1969-11-04', NULL),
    ('amy-adams',           'Эми Адамс',            '1974-08-20', NULL),
    ('james-s-a-corey',     'Джеймс Кори',          NULL,         'Псевдоним Дэниела Абрахама и Тая Френка.'),
    ('pedro-pascal',        'Педро Паскаль',        '1975-04-02', NULL),
    ('neil-druckmann',      'Нил Дракманн',         '1978-12-05', 'Сценарист и геймдиректор Naughty Dog.'),
    ('hidetaka-miyazaki',   'Хидэтака Миядзаки',    '1974-09-19', 'Геймдиректор FromSoftware.'),
    ('millie-bobby-brown',  'Милли Бобби Браун',    '2004-02-19', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO entity_tags (entity_id, tag_id)
SELECT (SELECT id FROM entities WHERE slug = v.entity), (SELECT id FROM tags WHERE slug = v.tag)
FROM (VALUES
    ('dune-novel', 'sci-fi'), ('dune-novel', 'space-opera'), ('dune-novel', 'classic'), ('dune-novel', 'philosophy'),
    ('dune-messiah', 'sci-fi'), ('dune-messiah', 'space-opera'),
    ('dune-1984', 'sci-fi'), ('dune-1984', 'space-opera'), ('dune-1984', 'based-on-book'),
    ('dune-2021', 'sci-fi'), ('dune-2021', 'space-opera'), ('dune-2021', 'based-on-book'), ('dune-2021', 'drama'),
    ('dune-part-two-2024', 'sci-fi'), ('dune-part-two-2024', 'space-opera'), ('dune-part-two-2024', 'based-on-book'),
    ('the-last-wish', 'fantasy'), ('the-last-wish', 'adventure'),
    ('the-witcher-series', 'fantasy'), ('the-witcher-series', 'based-on-book'), ('the-witcher-series', 'drama'),
    ('the-witcher-3-wild-hunt', 'fantasy'), ('the-witcher-3-wild-hunt', 'rpg'), ('the-witcher-3-wild-hunt', 'open-world'),
    ('the-hobbit-novel', 'fantasy'), ('the-hobbit-novel', 'adventure'), ('the-hobbit-novel', 'classic'),
    ('the-lord-of-the-rings-novel', 'fantasy'), ('the-lord-of-the-rings-novel', 'adventure'), ('the-lord-of-the-rings-novel', 'classic'),
    ('lotr-fellowship-2001', 'fantasy'), ('lotr-fellowship-2001', 'adventure'), ('lotr-fellowship-2001', 'based-on-book'),
    ('lotr-two-towers-2002', 'fantasy'), ('lotr-two-towers-2002', 'adventure'), ('lotr-two-towers-2002', 'based-on-book'),
    ('lotr-return-of-the-king-2003', 'fantasy'), ('lotr-return-of-the-king-2003', 'adventure'), ('lotr-return-of-the-king-2003', 'based-on-book'),
    ('the-hobbit-unexpected-journey-2012', 'fantasy'), ('the-hobbit-unexpected-journey-2012', 'adventure'), ('the-hobbit-unexpected-journey-2012', 'based-on-book'),
    ('the-shining-novel', 'horror'), ('the-shining-novel', 'classic'),
    ('the-shining-1980', 'horror'), ('the-shining-1980', 'thriller'), ('the-shining-1980', 'based-on-book'), ('the-shining-1980', 'classic'),
    ('it-novel', 'horror'), ('it-novel', 'drama'),
    ('it-2017', 'horror'), ('it-2017', 'based-on-book'),
    ('neuromancer', 'sci-fi'), ('neuromancer', 'cyberpunk'), ('neuromancer', 'classic'),
    ('do-androids-dream', 'sci-fi'), ('do-androids-dream', 'cyberpunk'), ('do-androids-dream', 'philosophy'),
    ('blade-runner-1982', 'sci-fi'), ('blade-runner-1982', 'cyberpunk'), ('blade-runner-1982', 'detective'), ('blade-runner-1982', 'based-on-book'),
    ('blade-runner-2049', 'sci-fi'), ('blade-runner-2049', 'cyberpunk'), ('blade-runner-2049', 'detective'), ('blade-runner-2049', 'dystopia'),
    ('cyberpunk-2077', 'sci-fi'), ('cyberpunk-2077', 'cyberpunk'), ('cyberpunk-2077', 'rpg'), ('cyberpunk-2077', 'open-world'),
    ('cyberpunk-edgerunners', 'cyberpunk'), ('cyberpunk-edgerunners', 'animation'), ('cyberpunk-edgerunners', 'drama'),
    ('roadside-picnic', 'sci-fi'), ('roadside-picnic', 'classic'), ('roadside-picnic', 'philosophy'),
    ('stalker-1979', 'sci-fi'), ('stalker-1979', 'philosophy'), ('stalker-1979', 'based-on-book'), ('stalker-1979', 'classic'),
    ('stalker-shadow-of-chernobyl', 'sci-fi'), ('stalker-shadow-of-chernobyl', 'shooter'), ('stalker-shadow-of-chernobyl', 'post-apocalypse'), ('stalker-shadow-of-chernobyl', 'open-world'),
    ('stalker-2', 'sci-fi'), ('stalker-2', 'shooter'), ('stalker-2', 'post-apocalypse'), ('stalker-2', 'open-world'),
    ('solaris-novel', 'sci-fi'), ('solaris-novel', 'philosophy'), ('solaris-novel', 'classic'),
    ('solaris-1972', 'sci-fi'), ('solaris-1972', 'philosophy'), ('solaris-1972', 'based-on-book'),
    ('nineteen-eighty-four', 'dystopia'), ('nineteen-eighty-four', 'classic'),
    ('a-game-of-thrones', 'fantasy'), ('a-game-of-thrones', 'drama'),
    ('game-of-thrones-series', 'fantasy'), ('game-of-thrones-series', 'drama'), ('game-of-thrones-series', 'based-on-book'),
    ('house-of-the-dragon', 'fantasy'), ('house-of-the-dragon', 'drama'), ('house-of-the-dragon', 'based-on-book'),
    ('metro-2033-novel', 'post-apocalypse'), ('metro-2033-novel', 'sci-fi'),
    ('metro-2033-game', 'post-apocalypse'), ('metro-2033-game', 'shooter'), ('metro-2033-game', 'horror'),
    ('metro-exodus', 'post-apocalypse'), ('metro-exodus', 'shooter'), ('metro-exodus', 'open-world'),
    ('interstellar', 'sci-fi'), ('interstellar', 'drama'),
    ('arrival-2016', 'sci-fi'), ('arrival-2016', 'drama'), ('arrival-2016', 'based-on-book'),
    ('leviathan-wakes', 'sci-fi'), ('leviathan-wakes', 'space-opera'), ('leviathan-wakes', 'detective'),
    ('the-expanse', 'sci-fi'), ('the-expanse', 'space-opera'), ('the-expanse', 'based-on-book'),
    ('mass-effect', 'sci-fi'), ('mass-effect', 'space-opera'), ('mass-effect', 'rpg'), ('mass-effect', 'shooter'),
    ('the-last-of-us', 'post-apocalypse'), ('the-last-of-us', 'horror'), ('the-last-of-us', 'drama'),
    ('the-last-of-us-series', 'post-apocalypse'), ('the-last-of-us-series', 'drama'),
    ('stranger-things', 'sci-fi'), ('stranger-things', 'horror'), ('stranger-things', 'adventure'),
    ('elden-ring', 'fantasy'), ('elden-ring', 'rpg'), ('elden-ring', 'open-world')
) AS v(entity, tag)
ON CONFLICT DO NOTHING;

INSERT INTO entity_credits (entity_id, person_id, role, character_name, position)
SELECT (SELECT id FROM entities WHERE slug = v.entity), (SELECT id FROM people WHERE slug = v.person),
       v.role, v.character_name, v.position
FROM (VALUES
    ('dune-novel',                         'frank-herbert',       'author',      NULL::text,             0),
    ('dune-messiah',                       'frank-herbert',       'author',      NULL,                   0),
    ('dune-1984',                          'david-lynch',         'director',    NULL,                   0),
    ('dune-1984',                          'kyle-maclachlan',     'actor',       'Пол Атрейдес',         1),
    ('dune-2021',                          'denis-villeneuve',    'director',    NULL,                   0),
    ('dune-2021',                          'timothee-chalamet',   'actor',       'Пол Атрейдес',         1),
    ('dune-2021',                          'zendaya',             'actor',       'Чани',                 2),
    ('dune-2021',                          'hans-zimmer',         'composer',    NULL,                   3),
    ('dune-part-two-2024',                 'denis-villeneuve',    'director',    NULL,                   0),
    ('dune-part-two-2024',                 'timothee-chalamet',   'actor',       'Пол Атрейдес',         1),
    ('dune-part-two-2024',                 'zendaya',             'actor',       'Чани',                 2),
    ('dune-part-two-2024',                 'hans-zimmer',         'composer',    NULL,                   3),
    ('the-last-wish',                      'andrzej-sapkowski',   'author',      NULL,                   0),
    ('the-witcher-series',                 'henry-cavill',        'actor',       'Геральт из Ривии',     1),
    ('the-hobbit-novel',                   'jrr-tolkien',         'author',      NULL,                   0),
    ('the-lord-of-the-rings-novel',        'jrr-tolkien',         'author',      NULL,                   0),
    ('lotr-fellowship-2001',               'peter-jackson',       'director',    NULL,                   0),
    ('lotr-fellowship-2001',               'elijah-wood',         'actor',       'Фродо Бэггинс',        1),
    ('lotr-fellowship-2001',               'ian-mckellen',        'actor',       'Гэндальф',             2),
    ('lotr-two-towers-2002',               'peter-jackson',       'director',    NULL,                   0),
    ('lotr-two-towers-2002',               'elijah-wood',         'actor',       'Фродо Бэггинс',        1),
    ('lotr-two-towers-2002',               'ian-mckellen',        'actor',       'Гэндальф',             2),
    ('lotr-return-of-the-king-2003',       'peter-jackson',       'director',    NULL,                   0),
    ('lotr-return-of-the-king-2003',       'elijah-wood',         'actor',       'Фродо Бэггинс',        1),
    ('lotr-return-of-the-king-2003',       'ian-mckellen',        'actor',       'Гэндальф',             2),
    ('the-hobbit-unexpected-journey-2012', 'peter-jackson',       'director',    NULL,                   0),
    ('the-hobbit-unexpected-journey-2012', 'ian-mckellen',        'actor',       'Гэндальф',             1),
    ('the-shining-novel',                  'stephen-king',        'author',      NULL,                   0),
    ('the-shining-1980',                   'stanley-kubrick',     'director',    NULL,                   0),
    ('the-shining-1980',                   'jack-nicholson',      'actor',       'Джек Торранс',         1),
    ('it-novel',                           'stephen-king',        'author',      NULL,                   0),
    ('it-2017',                            'andy-muschietti',     'director',    NULL,                   0),
    ('neuromancer',                        'william-gibson',      'author',      NULL,                   0),
    ('do-androids-dream',                  'philip-k-dick',       'author',      NULL,                   0),
    ('blade-runner-1982',                  'ridley-scott',        'director',    NULL,                   0),
    ('blade-runner-1982',                  'harrison-ford',       'actor',       'Рик Декард',           1),
    ('blade-runner-2049',                  'denis-villeneuve',    'director',    NULL,                   0),
    ('blade-runner-2049',                  'ryan-gosling',        'actor',       'К',                    1),
    ('blade-runner-2049',                  'harrison-ford',       'actor',       'Рик Декард',           2),
    ('blade-runner-2049',                  'hans-zimmer',         'composer',    NULL,                   3),
    ('cyberpunk-2077',                     'keanu-reeves',        'voice_actor', 'Джонни Сильверхенд',   1),
    ('roadside-picnic',                    'arkady-strugatsky',   'author',      NULL,                   0),
    ('roadside-picnic',                    'boris-strugatsky',    'author',      NULL,                   1),
    ('stalker-1979',                       'andrei-tarkovsky',    'director',    NULL,                   0),
    ('stalker-1979',                       'arkady-strugatsky',   'writer',      NULL,                   1),
    ('stalker-1979',                       'boris-strugatsky',    'writer',      NULL,                   2),
    ('solaris-novel',                      'stanislaw-lem',       'author',      NULL,                   0),
    ('solaris-1972',                       'andrei-tarkovsky',    'director',    NULL,                   0),
    ('nineteen-eighty-four',               'george-orwell',       'author',      NULL,                   0),
    ('a-game-of-thrones',                  'george-rr-martin',    'author',      NULL,                   0),
    ('game-of-thrones-series',             'pedro-pascal',        'actor',       'Оберин Мартелл',       1),
    ('house-of-the-dragon',                'george-rr-martin',    'writer',      NULL,                   0),
    ('metro-2033-novel',                   'dmitry-glukhovsky',   'author',      NULL,                   0),
    ('metro-2033-game',                    'dmitry-glukhovsky',   'writer',      NULL,                   0),
    ('interstellar',                       'christopher-nolan',   'director',    NULL,                   0),
    ('interstellar',                       'matthew-mcconaughey', 'actor',       'Купер',                1),
    ('interstellar',                       'hans-zimmer',         'composer',    NULL,                   2),
    ('arrival-2016',                       'denis-villeneuve',    'director',    NULL,                   0),
    ('arrival-2016',                       'amy-adams',           'actor',       'Луиза Бэнкс',          1),
    ('leviathan-wakes',                    'james-s-a-corey',     'author',      NULL,                   0),
    ('the-expanse',                        'james-s-a-corey',     'writer',      NULL,                   0),
    ('the-last-of-us',                     'neil-druckmann',      'writer',      NULL,                   0),
    ('the-last-of-us-series',              'neil-druckmann',      'creator',     NULL,                   0),
    ('the-last-of-us-series',              'pedro-pascal',        'actor',       'Джоэл Миллер',         1),
    ('stranger-things',                    'millie-bobby-brown',  'actor',       'Одиннадцать',          1),
    ('elden-ring',                         'hidetaka-miyazaki',   'director',    NULL,                   0),
    ('elden-ring',                         'george-rr-martin',    'writer',      NULL,                   1)
) AS v(entity, person, role, character_name, position)
ON CONFLICT DO NOTHING;

COMMIT;
